# https://github.com/netlify/netlify-cms/issues/386
# If using hexo: hexo generate; cp source/admin/config.yml public/admin/config.yml; rm public/admin/config.json
backend:
  name: github
  repo: sdfereday/netlifycms-test # Path to your Github repository
  branch: master # Branch to update

#publish_mode: editorial_workflow
media_folder: "/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "source" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Show As Home Page, name: home, widget: boolean}
      - name: section
        label: Section
        widget: list
        fields:
          - {name: body, label: Body, widget: markdown}